# Generated by Django 5.1.1 on 2024-10-01 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 0, 51, 811057))),
                ('datefin', models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 0, 51, 811057))),
                ('montantgaranti', models.DecimalField(decimal_places=3, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('regle', 'reglé'), ('encours', 'en cours')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=3, max_digits=16)),
                ('statut', models.CharField(choices=[('paye', 'payé'), ('retard', 'retard'), ('avance', 'avance')], max_length=50)),
            ],
        ),
    ]
