# Generated by Django 5.1.1 on 2024-10-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat', '0001_initial'),
        ('logement', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.locataire'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logement.logement'),
        ),
        migrations.AddField(
            model_name='dette',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrat.contrat'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contrat.contrat'),
        ),
    ]
