# Generated by Django 5.1.1 on 2024-10-01 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='datedebut',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 5, 39, 604247)),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datefin',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 12, 5, 39, 604247)),
        ),
    ]
