# Generated by Django 5.1.1 on 2024-10-02 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0004_alter_contrat_datedebut_alter_contrat_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='datedebut',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 11, 59, 48, 484076)),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datefin',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 11, 59, 48, 484076)),
        ),
    ]
