# Generated by Django 5.1.1 on 2024-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0009_alter_contrat_datedebut_alter_contrat_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='datedebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datefin',
            field=models.DateField(),
        ),
    ]
