# Generated by Django 5.1.1 on 2024-10-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('visiteur', 'visiteur'), ('gestionnaire', 'gestionnaire')], default='visiteur', max_length=50),
        ),
    ]
