# Generated by Django 5.1.1 on 2024-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('visiteur', 'visiteur'), ('locataire', 'locataire'), ('gestionnaire', 'gestionnaire')], default='visiteur', max_length=50),
        ),
    ]
