# Generated by Django 5.1.1 on 2024-10-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataire',
            name='nom',
        ),
    ]
